### PR TITLE
General tidying

### PR DESCRIPTION
**Pull request by arh-oxbotica**
- Modernise the main CMakeLists.txt files and generally spruce things up.
- Clean up the travis config.
- Remove some old build options that modified the MOOS ABI.
- Provide a MOOSConfig.cmake for 'make install'ed versions of MOOS.
- Ensure that installed binaries work correctly when shared libs are enabled.
- Ensure that binaries generated by the 'install' target are relocatable.
- Fix windows VS2012 build error with missing isnan function.

### CODE REVIEW

**Comment by msis** [comment]
This PR changes the definitions of the CMake module for MOOS. 
It is now impossible to compile any of the derivative projects: https://github.com/themoos/

**Comment by arh-oxbotica** [comment]
Thanks for pointing that out. I've submitted a new PR to address the regression introduced in #35. There is a separate regression introduced by an earlier commit (1e61cbb), which I think Paul's looking at.

**Comment by msis** [comment]
Thanks.
And include paths too will need to be rearranged.

**Comment by arh-oxbotica** [comment]
Not sure I understand what needs to happen to the include paths. Can you give some more detail?

If I revert commit 1e61cbb in core-moos then I'm able to build core-moos and all of the dependent projects on both MacOS and Ubuntu.

I'm aware of an issue with the INTERFACE_INCLUDE_PATH for the MOOS::MOOS target after a 'make install'. Will sort a fix for that shortly. Is that what you meant?

**Pull request merged**
