### PR TITLE
Many fixes, most related to MSVC build/linking (see each commit log for details); also tiny fixes to HTTP interface

### PR DESCRIPTION
**Pull request by jlblancoc**

### CODE REVIEW

**Comment by jlblancoc** [comment]
(@pmnewman This is the new one)

**Comment by pmnewman** [comment]
done

**Comment by pmnewman** [comment]
done
Prof. Paul Newman FREng FIEEE
BP Professor of Information Engineering
EPSRC Leadership Fellow
Dept Engineering Science
University of Oxford 

office +44 1865 283148
mobile +44 7545 341309


P.A Amy Fricker
+44 1865 283390

**Comment by jlblancoc** [comment]
:+1:  Thanks!! Will tell the guys to give a try to the release candidate... :-)

**Pull request merged**
