### PR TITLE
Devel: Fixed CMake problem and 2 build errors under Visual Studio

### PR DESCRIPTION
**Pull request by jlblancoc**
Please, refer to the self-explanatory diffs of the pull merge. 

Cheers,
Jose Luis

### CODE REVIEW

**Comment by pmnewman** [comment]
Hey Jose

I want to get to this but I'm not sure I can make it by Monday's release....

**Comment by jlblancoc** [comment]
Hi Paul!

Mmm... what a pity, it was a clean pull request back then. 
I'll try to rebase the commits or something alike, then open a new PR, hopefully by tomorrow (Saturday) afternoon...

**Comment by jlblancoc** [comment]
Will close this PR. A new, non-conflicting one is here ==> https://github.com/themoos/core-moos/pull/19

Cheers!

**Comment by pmnewman** [comment]
you are a legend
Prof. Paul Newman FREng FIEEE
BP Professor of Information Engineering
EPSRC Leadership Fellow
Dept Engineering Science
University of Oxford 

office +44 1865 283148
mobile +44 7545 341309


P.A Amy Fricker
+44 1865 283390

**Pull request closed without merging**
